# Generated by Django 3.2.5 on 2022-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('number', models.BigIntegerField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(0, 'MALE'), (1, 'female')])),
            ],
        ),
    ]
