# Generated by Django 3.2.5 on 2022-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
